### ISSUE TITLE
Error in lovelace when entity unavailable

### ISSUE THREAD

**Issue by DendelX** [bradcrc/color-lite-card#2]
Hi,

Nice custom! I have been using it for a few days and I found an issue. When an entity shows unavailable in ha, the whole view appears blank and cannot load lovelace. Entity should appear with the exclamation icon like other state-icons missing ones. 

Thanks in advance.

**Comment by bradcrc** [comment]
I thought that was addressed,  I haven't seen it since the last update but I'll try to recreate it.

**Comment by phinger** [comment]
Hi, sorry to bother but I don't know who to ask.
I have a manual installation of the Home Assistant latest version available on a raspbian.
In that installation there is no /js directory so I put the script /srv/homeassistant/lib/python3.7/site-packages/hass_frontend/static/images (that is available trough the browser), when I am in the preview It works perfectly but when I save the changes I get this error: "Cannot read property 'states' of undefined". Could you help me with this?
Thanks in advance!

**Comment by DendelX** [comment]
I have had to remove this card from my lovelace views. In each update it gives me problems and it seems not to be maintained since January. It  is a great solution for my floorplan but...
